### ISSUE TITLE
Clarify usage?

### ISSUE THREAD

**Issue by rpattcorner** [craighurley/aws-credentials-setup#1]
@craighurley, I was intrigued by your comment in AESR -- I mentioned in the thread there that my team supports commercial software to manage the lifecycle of large numbers of roles and principals.  Our focus is on the back end role creation and management, although we support the AESR plugin for our users.  

I'm trying to understand the aws-credentials-setup use case ... it looks like the idea is that an AWS administrator manages a single (encrypted) file of credentials in a YAML format, and processes it as a playbook to generate both the aws cli's creds & config file and the configuration file for AESR.  Is that correct, and is there more than that involved?  It looks like there are connections to SAML based federation as well.

**Comment by craighurley** [comment]
Hi @rpattcorner.

My comment on that other thread was a bit cheeky :) 

Yes, your right.  It creates 3 things for me:

1. AWS config and credentials files using this template: https://github.com/craighurley/aws-credentials-setup/blob/master/roles/credentials/templates/credentials.j2
2. AESR config using this template: https://github.com/craighurley/aws-credentials-setup/blob/master/roles/credentials/templates/extend_switch_roles.j2
3. Firefox containers config using this template: https://github.com/craighurley/aws-credentials-setup/blob/master/roles/credentials/templates/firefox_containers.j2

In the example `./vars/setup.yaml` in the README.md, I include reference to saml auth because for those organisations where I use saml to auth, I use the cli tool `saml2aws` (https://github.com/Versent/saml2aws) to generate temporary credentials.  `saml2aws` will update any existing dummy credentials in your aws credentials file.

The workflow is.

1. Create/update your `./vars/setup.yaml` usually on project kick-off/new AWS organisation.
2. Run `ansible-playbook ./playbooks/credentials.yaml` to generate all the files.
3. Copy AESR config into plugin in your browser.

After that, if you are working from the cli:
1. Authenticate for your AWS role (either IAM or SAML based).
2. Run AWS cli/sdk commands.

If you are simply using the AWS console
1. Login via the specific signin profile URL or federated login page.
2. AESR will do it's thing and present the appropriate roles for you.

**Comment by rpattcorner** [comment]
Thanks!  Clear as day, and appreciated.
